#!/usr/bin/env php
<?php

require realpath(__DIR__ . '/Import.php');

use PhpRepos\Cli\IO\Write;
use PhpRepos\Console\Config;
use PhpRepos\FileManager\Resolver;
use function Phpkg\Exception\register_exception_handler;

if (! empty(getopt('v::', ['version::']))) {
    Write\success('phpkg version 1.3.0');
    exit(0);
}

register_exception_handler();

$console_config = new Config(
    main_command_name: 'phpkg',
    default_commands_directory: 'Source\Commands',
    commands_file_suffix: '.php',
    help_text: <<<EOD
Usage: phpkg [-v | --version] [-h | --help]
               <command> [<options>] [<args>]
EOD,
);

require Resolver\realpath(__DIR__ . '/Packages/php-repos/console/console');
