#!/usr/bin/env php
<?php

require realpath(__DIR__ . '/Import.php');

use PhpRepos\Cli\IO\Write;
use PhpRepos\Console\Config;
use PhpRepos\FileManager\Path;
use PhpRepos\FileManager\Resolver;
use function Phpkg\Exception\register_exception_handler;

if (! empty(getopt('v::', ['version::']))) {
    Write\success('phpkg version 1.3.0');
    exit(0);
}

register_exception_handler();

$custom_console_config = new Config(
    commands_directory: Path::from_string(__DIR__ )->append('Source\Commands'),
    commands_file_suffix: '.php',
    additional_supported_options: '[-v | --version] ',
);

require Resolver\realpath(__DIR__ . '/Packages/php-repos/console/console');
