#!/usr/bin/env php
<?php

require realpath(__DIR__ . '/Import.php');
require_once realpath(__DIR__ . '/Tests/Helper.php');
require_once realpath(__DIR__ . '/Packages/php-repos/test-runner/Source/Assertions/Boolean.php');
require_once realpath(__DIR__ . '/Packages/php-repos/test-runner/Source/Assertions/Str.php');
require_once realpath(__DIR__ . '/Packages/php-repos/test-runner/Source/Runner.php');
require_once realpath(__DIR__ . '/Packages/php-repos/test-runner/run');
